### ISSUE TITLE
outgroup rooting

### ISSUE THREAD

**Issue by rvosa** [naturalis/supersmart#30]
The recent case with the Cucumis phylogeny shows that *BEAST does not necessarily root the tree correctly if it operates on the basis of substitution rates (i.e. a kind of midpoint rooting on steroids). It should therefore be possible for each *BEAST analysis to include one or more "nearby" species (e.g. from a sister genus) into the analysis, which are then pruned off when the resulting tree is grafted into the backbone.

**Comment by rvosa** [comment]
Unless I am not mistaken this functionality is now essentially available in that we can now add the argument `--add-outgroups` to the `bbdecompose` subcommand, which automatically adds an outgroup to each clade for which it will run *BEAST. I think this issue can therefore be closed?

**Comment by hettling** [comment]
This is not fully functional yet. So far, it is possible to add an outgroup when running 'BBdecompose'. These outgroup species should be pruned from the tree at a later stage after 'Cladeinfer'. This is not implemented yet.

**Comment by rvosa** [comment]
By the way, I notice that running `bbdecompose` with the outgroup flag `-g` is a bit sensitive, as one might expect: in the case of _Piper_ and _Peperomia_ there is actually no outgroup in the other genus for the respective genera so no alignments are selected. In this case the rooting within the clades appears to be OK anyway (not a lot of rate variation, I guess?)

**Comment by hettling** [comment]
Adding of outgroups is now implemented to not mess with the selection of the clade alignments too much: If `-g` option is set, select a sister node of the mrca of each clade (ideally this will be a sister-genus) and select up to four species that occur in most of the alignments. 
I do not count the outgroup species in the clade density statistics, since this could exclude alignments which would otherwise be included. 
It can of course happen that no alignment from a sister genus is good enough to be included in a clade (e.g. if it only contains markers sequenced for one clade and not the other). However, for larger datasets, selecting outgroup species that occur in most alignments seems like the safest bet.
Please tell me if you agree and I can close this issue.

**Comment by hettling** [comment]
By the way, for *Piper* and *Peperomia*, what do you take for `CLADE_MIN_DENSITY`? The default value 0.5 results in only one alignment per clade for me.

**Comment by rvosa** [comment]
I took the default, which resulted in something like one alignment per clade (I thought it was one for one genus and two for the other?).

**Comment by hettling** [comment]
Automatically including outgroups into clades works now. Up to four outgroup species from a sister genus are added per clade, where we take the species having the most overlapping markers with this clade. If the -g option in *bbdecompose* is set, the outgroup species are written into the file *outgroup.txt* in each clade folder.

After running BEAST, when invoking *cladegraft*, the outgroup file is parsed in each clade folder and the outgroup species are removed from the tree. However, we keep a copy of the consensus tree which includes the outgroup species so one can make sure that the outgroup is the basal group in the consensus.

We then have for example:
clade0/clade0.dnd
clade0/clade0-remapped.dnd
clade0/clade0-pruned.dnd
clade0/clade0-pruned-remapped.dnd
