### ISSUE TITLE
Tag with version number

### ISSUE THREAD

**Issue by rvosa** [naturalis/supersmart#33]
Once all the milestone issues are resolved and we're happy with everything we should tag the repo state as v1.0.0-RC1 (or *-beta?) so that we can make a snapshot release that goes with the publication.

**Comment by hettling** [comment]
Added an initial  release number (0.0.1). Releases follow the semantic versioning system (MAJOR.MINOR.PATCH). The third digit is increased when performing minor changes and bug fixes. The second digit is increased with (minor) backwards-compatible changes, such as adding functionality. The first digit is meant for major or backwards incompatible changes. 
Version 0.x.x indicates that this is still the development version.

If a new release is created, the version number *must* be bumped in supersmart.ini (see also commit 6f4a574ab2e0c669a443dbd13f5510fe483240f8). 

To display current release version, the command 'smrt version' can be invoked. Also, the current release version is written as first log message when invoking any subcommand.

The download links on the website now point to the current release version instead of the head of the master branch. This way, the master branch can still be a 'bleeding edge' development branch that occasionally releases a stable version.
