### ISSUE TITLE
publish provisioned VM in Vagrant cloud

### ISSUE THREAD

**Issue by hettling** [naturalis/supersmart#41]
Since Supersmart has many dependencies from different parties, errors during provisioning are not uncommon (e.g. a download server fails). Offering a machine that is already provisioned would overcome this since only one large file has to be downloaded. The box file can be easily made available via the vagrant cloud. 
It is important to make sure however, that the SUPERSMART source always gets updated to the latest release.

**Comment by rvosa** [comment]
I wonder if there is a way to make this as issue as possible, so that a VM gets generated and published more or less automatically.

**Comment by rvosa** [comment]
For the next VM we need to make sure that we compile RAxML from make file `Makefile.SSE3.PTHREADS.gcc`, assuming that this is indeed the lowest common denominator, as per issue #53

**Comment by rvosa** [comment]
To make an image:
* download ubuntu box
* check out this repo into it
* run puppet apply
* box it up
(upload)

**Comment by rvosa** [comment]
Now that the puppet manifest is up to date and continuously tested (with, today, all tests passing) the job essentially becomes:
* download ubuntu box
* install puppet on it
* apply the puppet manifest
* run cpanm inside $SUPERSMART_HOME
In other words, the steps in .travis.yml.

**Comment by rvosa** [comment]
Mmmm... this looks tempting: https://docs.docker.com/docker-hub/builds/

**Comment by rvosa** [comment]
The webhooks provided by github are something we would really like to be able to work with. The basic idea is that whenever we tag a version increase, github will trigger a request, which we would then want to lead to the provisioning and uploading of a fresh vagrant box. One of the issues with this is that we are normally behind a firewall so github cannot reach us. Of course people are working on solutions for this, such as http://www.ultrahook.com/ or http://www.lshift.net/blog/2009/07/21/webhooks-behind-the-firewall-with-reverse-http/

**Comment by rvosa** [comment]
Or this? Directly via travis? https://atlas.hashicorp.com/help/guides/continuous-integration

**Comment by hettling** [comment]
This looks good, I missed that vagrant cloud is now part of Atlas! So simple box operations such as updating should still be possible: https://vagrantcloud.com/docs/boxes

**Comment by hettling** [comment]
**Packer** seems to do what we want regarding publishing the VM: The command `packer push` takes a simple json configuration file with info about provisioning etc, builds the VM on the ATLAS server and adds it to the boxes in our account: 

https://www.packer.io/intro/getting-started/setup.html

It also supports amazon cloud, docker and VMware

**Comment by rvosa** [comment]
`make vagrant` has now resulted in a functioning VM (all unit tests pass), on my laptop, with downloads over slow wifi. This is good enough to run as something like a cron job on the desktop, I think.

**Comment by rvosa** [comment]
Actually, I'm now working my way through packer, it seems to be pretty doable. We should be able to kick off a packer push every time a travis test run succeeds.

**Comment by hettling** [comment]
I still get the error ` g++: internal compiler error: Killed (program cc1plus)` which probably is due to memory issues

**Comment by rvosa** [comment]
Recent commits (around d544e15fb63f2da572bfc4b485da7acd4983bb36) are working towards an automated system where travis pushes to atlas to create and host a vagrant box.

**Comment by rvosa** [comment]
The main outstanding task before closing this issue is as follows: we now have multiple version numbers, one in Bio::SUPERSMART, one in template.json, and the git tags. We want the git tags to be definitive, for example because these are also linked to zenodo DOIs. Therefore, when a new tag is applied, a script that is run by travis after the unit tests should do the following:
- get the most recent git version tag, e.g. `git describe --tags | cut -f1 -d '-'`
- get the Bio::SUPERSMART version, e.g. `perl -MBio::SUPERSMART -e 'print $Bio::SUPERSMART::VERSION'`
- if there's a mismatch, search and replace lib/Bio/SUPERSMART.pm and conf/template.json
- commit these changes. Travis needs to do this, so there's some jiggery pokery with encrypted OAuth tokens
- do a packer push

**Comment by rvosa** [comment]
As of commit 023d6834d1d36b5fc0aba2db2d28951d98fa24f2 the version numbers are reconciled by `conf/update_version.sh`, while commit 5152c4fc3f090080162e62315709401c97df5db4 has the git pushing in `.travis.yml`.

**Comment by rvosa** [comment]
The automation with Atlas is now almost, but not quite, working. The important bug bear that still keeps me from closing this issue is that the guest additions are somehow not getting installed correctly. Commit 5c7120d2299a94b91abd5c0f14d7fa9e0e3f5c42 should have fixed this, now needs to run through travis, then atlas, then vagrant init and see if we get a sync'ed folder.

**Comment by rvosa** [comment]
We now have a fully functioning [SUPERSMART v0.1.18](https://atlas.hashicorp.com/Naturalis/boxes/supersmart/versions/0.1.18) on the vagrant cloud, which corresponds with [git tag v0.1.18](https://github.com/naturalis/supersmart/tree/v0.1.18). To release a new version, do the following:
- make sure `packer` is installed and configured correctly
- check to see which tag version to assign (i.e. at time of writing the next release would be v0.1.19)
- cd into `conf` and run `./update_version.sh v0.1.19`
This will update the version number in `conf/template.json` and `lib/Bio/SUPERSMART.pm`, tag the repository and push to github and atlas.
